apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: maritime-vacation-site

resources:
  - namespace.yaml
  - image-refresh-rbac.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - image-refresh-hook.yaml
