apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-storage
  namespace: media  # We can keep it in media namespace since it's the primary storage
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local-path
  resources:
    requests:
      storage: 3500Gi  # Nearly full RAID1 capacity 