apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads-storage
  namespace: downloads
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local-path
  resources:
    requests:
      storage: 500Gi  # Temporary storage for downloads before moving to media 