apiVersion: v1
kind: PersistentVolume
metadata:
  name: dev-data
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: dev_storage    # This will be relative to the repo root
  storageClassName: local-path