apiVersion: v1
kind: PersistentVolume
metadata:
  name: dev-data
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /tmp/k8s_nas_dev    # This directory will be in .gitignore 