apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: apps
  namespace: argocd
spec:
  description: "Applications project for user workloads"
  
  sourceRepos:
  - 'https://github.com/brettswift/k8s_nas.git'
  
  destinations:
  - namespace: 'demo'
    server: https://kubernetes.default.svc
  - namespace: 'media'
    server: https://kubernetes.default.svc
  - namespace: 'homepage'
    server: https://kubernetes.default.svc
  - namespace: 'default'
    server: https://kubernetes.default.svc
  
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  - group: 'networking.k8s.io'
    kind: Ingress
  
  namespaceResourceWhitelist:
  - group: ''
    kind: ConfigMap
  - group: ''
    kind: Secret
  - group: ''
    kind: Service
  - group: ''
    kind: Deployment
  - group: 'apps'
    kind: Deployment
  - group: 'apps'
    kind: StatefulSet
  - group: 'apps'
    kind: DaemonSet
  - group: 'networking.k8s.io'
    kind: Ingress
  - group: 'networking.istio.io'
    kind: Gateway
  - group: 'networking.istio.io'
    kind: VirtualService
  - group: 'batch'
    kind: Job
  - group: 'batch'
    kind: CronJob
