apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: nas
  namespace: argocd
spec:
  description: "NAS Media Server Project"
  
  sourceRepos:
  - 'https://github.com/brettswift/k8s_nas.git'
  
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc
  
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  - group: 'networking.k8s.io'
    kind: Ingress
  - group: 'networking.k8s.io'
    kind: NetworkPolicy
  - group: 'argoproj.io'
    kind: ApplicationSet
  
  namespaceResourceWhitelist:
  - group: ''
    kind: ConfigMap
  - group: ''
    kind: Secret
  - group: ''
    kind: Service
  - group: ''
    kind: Deployment
  - group: ''
    kind: Pod
  - group: 'apps'
    kind: Deployment
  - group: 'apps'
    kind: StatefulSet
  - group: 'networking.k8s.io'
    kind: Ingress
