apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: nas
  namespace: argocd
spec:
  description: Home NAS Project
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*' 