apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: monitoring
data:
  promtail.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0

    positions:
      filename: /run/promtail/positions.yaml

    clients:
      - url: http://loki:3100/loki/api/v1/push

    scrape_configs:
      - job_name: container-logs
        static_configs:
          - targets: [localhost]
            labels:
              job: container-logs
              __path__: /var/log/containers/*.log
        relabel_configs:
          - action: replace
            source_labels: [__path__]
            regex: /var/log/containers/([^_]+)_([^_]+)_([^-.]+)-[0-9a-f]+\\.log
            target_label: pod
            replacement: $1
          - action: replace
            source_labels: [__path__]
            regex: /var/log/containers/([^_]+)_([^_]+)_([^-.]+)-[0-9a-f]+\\.log
            target_label: namespace
            replacement: $2
          - action: replace
            source_labels: [__path__]
            regex: /var/log/containers/([^_]+)_([^_]+)_([^-.]+)-[0-9a-f]+\\.log
            target_label: container
            replacement: $3
          - action: drop
            source_labels: [namespace]
            regex: kube-system|kube-public|kube-node-lease
        pipeline_stages:
          - cri: {}
