apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: sample-hello-gateway
  labels:
    app.kubernetes.io/name: sample-hello
    app.kubernetes.io/instance: sample-hello
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: sample-hello-vs
  labels:
    app.kubernetes.io/name: sample-hello
    app.kubernetes.io/instance: sample-hello
spec:
  hosts:
  - "*"
  gateways:
  - sample-hello-gateway
  http:
  - match:
    - uri:
        prefix: /demo
    route:
    - destination:
        host: sample-hello
        port:
          number: 8080
