apiVersion: batch/v1
kind: CronJob
metadata:
  name: qbittorrent-scraper
  namespace: qbittorrent
spec:
  # Run every hour at minute 0
  schedule: "0 * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: scraper
            image: python:3.11-alpine
            command:
            - /bin/sh
            - -c
            - |
              pip install --no-cache-dir requests
              python3 /scripts/scrape-ext-to.py
            env:
            - name: SCRAPE_URL
              value: "https://apibay.org/q.php?q=user:smcgill1969"
            - name: QBT_URL
              # Use service name since we're in a separate pod
              # Note: Configure qBittorrent to bypass auth for cluster subnet (10.42.0.0/16)
              # In qBittorrent UI: Tools → Options → Web UI → Bypass authentication for clients in whitelisted IP subnets
              # Add: 10.42.0.0/16
              value: "http://qbittorrent.qbittorrent.svc.cluster.local:8080"
            - name: CHECK_INTERVAL
              value: "3600"  # 1 hour (not used in cron mode, but kept for compatibility)
            - name: STATE_FILE
              value: "/config/scraper-state.json"
            - name: TEST_MODE
              value: "false"
            - name: CRON_MODE
              value: "true"
            resources:
              requests:
                cpu: "50m"
                memory: "128Mi"
              limits:
                cpu: "200m"
                memory: "256Mi"
            volumeMounts:
            - name: qbittorrent-scripts
              mountPath: /scripts
              readOnly: true
            - name: qbittorrent-config
              mountPath: /config
          volumes:
          - name: qbittorrent-scripts
            configMap:
              name: qbittorrent-scripts
              defaultMode: 0755
          - name: qbittorrent-config
            persistentVolumeClaim:
              claimName: qbittorrent-config
          restartPolicy: OnFailure

