apiVersion: batch/v1
kind: CronJob
metadata:
  name: qbittorrent-scraper
  namespace: qbittorrent
spec:
  # Run every hour at minute 0
  schedule: "0 * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: scraper
            # Custom image with requests pre-installed (no pip install on every run)
            # Build on server with: cd apps/media-services/qbittorrent && ./build-scraper-image.sh
            # Image is tagged with git commit hash for cache invalidation on new deployments
            image: qbittorrent-scraper:latest
            imagePullPolicy: Never  # Use local image (k3s will use Docker images on host)
            command:
            - python3
            - /scripts/torrent-scraper.py
            env:
            - name: SCRAPE_URL
              value: "https://apibay.org/q.php?q=user:smcgill1969"
            - name: QBT_URL
              # Use service name since we're in a separate pod
              # Note: Configure qBittorrent to bypass auth for cluster subnet (10.0.0.0/8 covers 10.42.0.0/16)
              value: "http://qbittorrent.qbittorrent.svc.cluster.local:8080"
            - name: CHECK_INTERVAL
              value: "3600"  # 1 hour (not used in cron mode, but kept for compatibility)
            - name: STATE_FILE
              value: "/config/scraper-state.json"
            - name: LOG_FILE
              value: "/var/log/scraper.log"
            - name: TEST_MODE
              value: "false"
            - name: CRON_MODE
              value: "true"
            - name: CATEGORY
              value: "formula1"
            - name: SAVE_PATH
              value: "/data/media/formula1"
            - name: MAX_AGE_DAYS
              value: "7"  # Only add torrents added within last week
            - name: SEQUENTIAL_DOWNLOAD
              value: "true"
            resources:
              requests:
                cpu: "50m"
                memory: "128Mi"
              limits:
                cpu: "200m"
                memory: "256Mi"
            volumeMounts:
            - name: qbittorrent-scripts
              mountPath: /scripts
              readOnly: true
            - name: qbittorrent-config
              mountPath: /config
          volumes:
          - name: qbittorrent-scripts
            configMap:
              name: qbittorrent-scripts
              defaultMode: 0755
          - name: qbittorrent-config
            persistentVolumeClaim:
              claimName: qbittorrent-config
          restartPolicy: OnFailure

