apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scraper-pip-cache
  namespace: qbittorrent
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: local-path

