apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- pvc.yaml
- deployment.yaml
- service.yaml
- image-refresh-hook.yaml
- image-refresh-rbac.yaml
- race-manager-cronjob.yaml
