apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: f1-mock-api-data
  namespace: f1-predictor-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
  storageClassName: local-path
