apiVersion: v1
kind: Service
metadata:
  name: f1-mock-api
  namespace: f1-predictor-dev
  labels:
    app: f1-mock-api
spec:
  selector:
    app: f1-mock-api
  ports:
  - name: http
    port: 80
    targetPort: 5000
    protocol: TCP
  type: ClusterIP
