apiVersion: v1
kind: ServiceAccount
metadata:
  name: image-refresh
  namespace: f1-predictor
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: image-refresh
  namespace: f1-predictor
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: image-refresh
  namespace: f1-predictor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: image-refresh
subjects:
- kind: ServiceAccount
  name: image-refresh
  namespace: f1-predictor
