apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: f1-predictor

resources:
- namespace.yaml
- ../../base
- ingress.yaml
- driver-refresh-cronjob.yaml

patches:
- path: deployment-patch.yaml

images:
- name: ghcr.io/brettswift/f1-predictor:latest
  newName: ghcr.io/brettswift/f1-predictor
  newTag: live
