apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: travel-planner-data
  namespace: travel-planner
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
