apiVersion: v1
kind: Service
metadata:
  name: travel-planner
  namespace: travel-planner
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3000
    targetPort: http
  selector:
    app: travel-planner
