apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: nas
  namespace: argocd
spec:
  description: "NAS Media Server Project"
  
  sourceRepos:
  - 'https://github.com/brettswift/docker-compose-nas.git'
  - 'https://github.com/brettswift/k8s_nas.git'
  
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc
  
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  - group: ''
    kind: PersistentVolume
  - group: ''
    kind: PersistentVolumeClaim
  - group: ''
    kind: StorageClass
  - group: 'networking.k8s.io'
    kind: Ingress
  - group: 'networking.k8s.io'
    kind: NetworkPolicy
  
  namespaceResourceWhitelist:
  - group: ''
    kind: ConfigMap
  - group: ''
    kind: Secret
  - group: ''
    kind: Service
  - group: ''
    kind: Deployment
  - group: ''
    kind: StatefulSet
  - group: ''
    kind: Pod
  - group: 'apps'
    kind: Deployment
  - group: 'apps'
    kind: StatefulSet
  - group: 'apps'
    kind: ReplicaSet
  - group: 'extensions'
    kind: Ingress
  - group: 'networking.k8s.io'
    kind: Ingress
  - group: 'networking.istio.io'
    kind: VirtualService
  - group: 'networking.istio.io'
    kind: Gateway
  - group: 'networking.istio.io'
    kind: DestinationRule
  - group: 'cert-manager.io'
    kind: Certificate
  - group: 'cert-manager.io'
    kind: ClusterIssuer
  - group: 'cert-manager.io'
    kind: Issuer
