apiVersion: batch/v1
kind: CronJob
metadata:
  name: starr-integration-reconciler
  namespace: media
  labels:
    app: starr-integration-configurator
    purpose: reconciliation
spec:
  # Run every 6 hours - exits early if already configured (idempotent)
  schedule: "0 */6 * * *"
  # Keep last 3 successful jobs and 1 failed job for debugging
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  # Prevent concurrent executions
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      # Job will exit immediately if already configured (idempotent)
      backoffLimit: 2
      ttlSecondsAfterFinished: 3600  # Clean up after 1 hour
      template:
        metadata:
          labels:
            app: starr-integration-configurator
            purpose: reconciliation
        spec:
          serviceAccountName: starr-integration-configurator
          restartPolicy: Never
          containers:
          - name: configurator
            # Same as Job - uses inline script for now
            # TODO: Build custom image or use ConfigMap
            image: curlimages/curl:latest
            command: ["/bin/sh"]
            args:
              - -c
              - |
                apk add --no-cache jq bash > /dev/null 2>&1 || true
                /bin/bash <<'EOF'
                set -e
                SONARR_URL="${SONARR_URL:-http://sonarr.media.svc.cluster.local:8989}"
                PROWLARR_URL="${PROWLARR_URL:-http://prowlarr.media.svc.cluster.local:9696}"
                SONARR_KEY="${SONARR_API_KEY}"
                PROWLARR_KEY="${PROWLARR_API_KEY}"
                
                echo "ðŸ” Checking integration status..."
                
                # Quick health check
                if ! curl -s -f -H "X-Api-Key: ${SONARR_KEY}" "${SONARR_URL}/api/v3/system/status" > /dev/null 2>&1 || \
                   ! curl -s -f -H "X-Api-Key: ${PROWLARR_KEY}" "${PROWLARR_URL}/api/v1/system/status" > /dev/null 2>&1; then
                  echo "âš ï¸  Services not ready, skipping reconciliation"
                  exit 0
                fi
                
                # Idempotent check - if already configured, exit early
                EXISTING_INDEXER=$(curl -s -H "X-Api-Key: ${SONARR_KEY}" "${SONARR_URL}/api/v3/indexer" 2>/dev/null | jq -r '.[] | select(.implementation == "Prowlarr") | .id' | head -1 || echo "")
                EXISTING_APP=$(curl -s -H "X-Api-Key: ${PROWLARR_KEY}" "${PROWLARR_URL}/api/v1/applications" 2>/dev/null | jq -r '.[] | select(.name == "Sonarr") | .id' | head -1 || echo "")
                
                if [ -n "$EXISTING_INDEXER" ] && [ -n "$EXISTING_APP" ]; then
                  echo "âœ… Integration already configured - no action needed"
                  exit 0
                fi
                
                # If not configured, configure it
                echo "âš ï¸  Integration missing or incomplete - configuring..."
                
                # Configure Sonarr â†’ Prowlarr if needed
                if [ -z "$EXISTING_INDEXER" ]; then
                  echo "Adding Prowlarr indexer to Sonarr..."
                  curl -s -X POST -H "Content-Type: application/json" -H "X-Api-Key: ${SONARR_KEY}" \
                    -d "{\"name\":\"Prowlarr\",\"implementation\":\"Prowlarr\",\"fields\":[{\"name\":\"baseUrl\",\"value\":\"${PROWLARR_URL}\"},{\"name\":\"apiKey\",\"value\":\"${SONARR_KEY}\"},{\"name\":\"syncLevel\",\"value\":\"fullSync\"}]}" \
                    "${SONARR_URL}/api/v3/indexer" > /dev/null
                fi
                
                # Configure Prowlarr â†’ Sonarr if needed
                if [ -z "$EXISTING_APP" ]; then
                  echo "Adding Sonarr application to Prowlarr..."
                  curl -s -X POST -H "Content-Type: application/json" -H "X-Api-Key: ${PROWLARR_KEY}" \
                    -d "{\"name\":\"Sonarr\",\"syncLevel\":\"addAndRemoveOnly\",\"implementation\":\"Sonarr\",\"fields\":[{\"name\":\"baseUrl\",\"value\":\"${SONARR_URL}\"},{\"name\":\"apiKey\",\"value\":\"${SONARR_KEY}\"},{\"name\":\"syncAppIndexers\",\"value\":true}]}" \
                    "${PROWLARR_URL}/api/v1/applications" > /dev/null
                fi
                
                echo "âœ… Reconciliation complete"
EOF
            env:
            - name: SONARR_URL
              valueFrom:
                configMapKeyRef:
                  name: starr-common-config
                  key: SONARR_URL
            - name: PROWLARR_URL
              valueFrom:
                configMapKeyRef:
                  name: starr-common-config
                  key: PROWLARR_URL
            - name: SONARR_API_KEY
              valueFrom:
                secretKeyRef:
                  name: starr-secrets
                  key: SONARR_API_KEY
            - name: PROWLARR_API_KEY
              valueFrom:
                secretKeyRef:
                  name: starr-secrets
                  key: PROWLARR_API_KEY
            resources:
              requests:
                memory: "64Mi"
                cpu: "50m"
              limits:
                memory: "128Mi"
                cpu: "200m"

