apiVersion: batch/v1
kind: Job
metadata:
  name: starr-integration-configurator
  namespace: media
  labels:
    app: starr-integration-configurator
    purpose: configuration
  annotations:
    # Allow ArgoCD to replace this Job (since Jobs are immutable once created)
    argocd.argoproj.io/sync-options: Replace=true
spec:
  # Don't restart on failure - manual trigger or CronJob handles retries
  backoffLimit: 3
  # Clean up completed jobs after 1 hour
  ttlSecondsAfterFinished: 3600
  template:
    metadata:
      labels:
        app: starr-integration-configurator
        purpose: configuration
    spec:
      serviceAccountName: starr-integration-configurator
      restartPolicy: Never
      containers:
      - name: configurator
        # Use a lightweight image with curl and jq
        # TODO: Build and push to registry, or use a public image
        # For now, using a base image - will need to build or use existing script
        image: alpine:3.20
        command: ["/bin/sh"]
        args:
          - -c
          - |
            # Install dependencies
            apk add --no-cache curl jq > /dev/null 2>&1
            # Main configuration script - handles Sonarr and Radarr
            /bin/sh <<'EOF'
            set -e
            
            SONARR_URL="${SONARR_URL:-http://sonarr.media.svc.cluster.local:8989}"
            RADARR_URL="${RADARR_URL:-http://radarr.media.svc.cluster.local:7878}"
            PROWLARR_URL="${PROWLARR_URL:-http://prowlarr.media.svc.cluster.local:9696}"
            
            SONARR_KEY="${SONARR_API_KEY}"
            RADARR_KEY="${RADARR_API_KEY}"
            PROWLARR_KEY="${PROWLARR_API_KEY}"
            
            echo "🔗 Starr Integration Configurator"
            echo "=================================="
            echo ""
            
            # Function to check if service is ready
            check_service() {
              local url=$1
              local key=$2
              local name=$3
              local api_version=$4
              
              if curl -s -f -L -H "X-Api-Key: ${key}" "${url}/api/${api_version}/system/status" > /dev/null 2>&1; then
                echo "✅ $name is ready"
                return 0
              else
                echo "⚠️  $name not ready"
                return 1
              fi
            }
            
            # Wait for services (gracefully handle missing services)
            echo "Checking service availability..."
            SONARR_READY=false
            RADARR_READY=false
            PROWLARR_READY=false
            
            if [ -n "$SONARR_KEY" ] && check_service "$SONARR_URL" "$SONARR_KEY" "Sonarr" "v3"; then
              SONARR_READY=true
            fi
            
            if [ -n "$RADARR_KEY" ] && check_service "$RADARR_URL" "$RADARR_KEY" "Radarr" "v3"; then
              RADARR_READY=true
            fi
            
            if [ -n "$PROWLARR_KEY" ] && check_service "$PROWLARR_URL" "$PROWLARR_KEY" "Prowlarr" "v1"; then
              PROWLARR_READY=true
            fi
            
            if [ "$PROWLARR_READY" = false ]; then
              echo "❌ Prowlarr is required but not ready"
              exit 1
            fi
            
            if [ "$SONARR_READY" = false ] && [ "$RADARR_READY" = false ]; then
              echo "⚠️  Neither Sonarr nor Radarr is ready - nothing to configure"
              exit 0
            fi
            
            echo ""
            echo "Starting configuration..."
            echo ""
            
            CONFIGURED_COUNT=0
            TOTAL_COUNT=0
            
            # Configure Sonarr ↔ Prowlarr
            if [ "$SONARR_READY" = true ]; then
              TOTAL_COUNT=$((TOTAL_COUNT + 2))
              
              echo "=== Sonarr ↔ Prowlarr Integration ==="
              
              # Check if Prowlarr indexer exists in Sonarr
              EXISTING_INDEXER=$(curl -s -L -H "X-Api-Key: ${SONARR_KEY}" "${SONARR_URL}/api/v3/indexer" 2>/dev/null | jq -r '.[] | select(.implementation == "Prowlarr") | .id' | head -1 || echo "")
              
              if [ -n "$EXISTING_INDEXER" ]; then
                echo "✅ Sonarr → Prowlarr: Already configured"
                CONFIGURED_COUNT=$((CONFIGURED_COUNT + 1))
              else
                echo "Configuring Sonarr → Prowlarr..."
                # Get schema first to understand field structure
                SCHEMA=$(curl -s -L -H "X-Api-Key: ${SONARR_KEY}" "${SONARR_URL}/api/v3/indexer/schema" 2>/dev/null)
                PROWLARR_SCHEMA=$(echo "$SCHEMA" | jq -r '.[] | select(.implementation == "Prowlarr")')
                
                # Build proper JSON payload using schema - preserve all field properties
                PAYLOAD=$(echo "$PROWLARR_SCHEMA" | jq --arg url "${PROWLARR_URL}" --arg key "${SONARR_KEY}" '{
                  name: .name,
                  implementation: .implementation,
                  configContract: .configContract,
                  enableRss: true,
                  enableAutomaticSearch: true,
                  enableInteractiveSearch: true,
                  priority: 25,
                  fields: (.fields | map(
                    if .name == "baseUrl" then .value = $url
                    elif .name == "apiKey" then .value = $key
                    elif .name == "syncLevel" then .value = "fullSync"
                    else if (.value == null) then .value = "" else . end
                    end
                  ))
                }')
                
                RESPONSE=$(curl -s -L -w "\n%{http_code}" -X POST \
                  -H "Content-Type: application/json" \
                  -H "X-Api-Key: ${SONARR_KEY}" \
                  -d "$PAYLOAD" \
                  "${SONARR_URL}/api/v3/indexer" 2>/dev/null || echo -e "\n000")
                HTTP_CODE=$(echo "$RESPONSE" | tail -1)
                BODY=$(echo "$RESPONSE" | head -n -1)
                if [ "$HTTP_CODE" = "201" ] || [ "$HTTP_CODE" = "200" ]; then
                  echo "✅ Sonarr → Prowlarr: Configured"
                  CONFIGURED_COUNT=$((CONFIGURED_COUNT + 1))
                else
                  echo "⚠️  Sonarr → Prowlarr: Failed (HTTP $HTTP_CODE)"
                  echo "   Response: $(echo "$BODY" | head -c 200)"
                fi
              fi
              
              # Check if Sonarr application exists in Prowlarr
              EXISTING_APP=$(curl -s -L -H "X-Api-Key: ${PROWLARR_KEY}" "${PROWLARR_URL}/api/v1/applications" 2>/dev/null | jq -r '.[] | select(.name == "Sonarr") | .id' | head -1 || echo "")
              
              if [ -n "$EXISTING_APP" ]; then
                echo "✅ Prowlarr → Sonarr: Already configured"
                CONFIGURED_COUNT=$((CONFIGURED_COUNT + 1))
              else
                echo "Configuring Prowlarr → Sonarr..."
                # Get schema for Sonarr application
                SCHEMA=$(curl -s -L -H "X-Api-Key: ${PROWLARR_KEY}" "${PROWLARR_URL}/api/v1/applications/schema" 2>/dev/null)
                SONARR_SCHEMA=$(echo "$SCHEMA" | jq -r '.[] | select(.implementation == "Sonarr")')
                
                # Build proper JSON payload - preserve all field properties
                PAYLOAD=$(echo "$SONARR_SCHEMA" | jq --arg url "${SONARR_URL}" --arg key "${SONARR_KEY}" '{
                  name: .name,
                  syncLevel: "addAndRemoveOnly",
                  implementation: .implementation,
                  configContract: .configContract,
                  fields: (.fields | map(
                    if .name == "baseUrl" then .value = $url
                    elif .name == "apiKey" then .value = $key
                    elif .name == "syncAppIndexers" then .value = true
                    elif .name == "appIndexersSyncLevel" then .value = "addAndRemoveOnly"
                    else if (.value == null) then .value = "" else . end
                    end
                  ))
                }')
                
                RESPONSE=$(curl -s -L -w "\n%{http_code}" -X POST \
                  -H "Content-Type: application/json" \
                  -H "X-Api-Key: ${PROWLARR_KEY}" \
                  -d "$PAYLOAD" \
                  "${PROWLARR_URL}/api/v1/applications" 2>/dev/null || echo -e "\n000")
                HTTP_CODE=$(echo "$RESPONSE" | tail -1)
                BODY=$(echo "$RESPONSE" | head -n -1)
                if [ "$HTTP_CODE" = "201" ] || [ "$HTTP_CODE" = "200" ]; then
                  echo "✅ Prowlarr → Sonarr: Configured"
                  CONFIGURED_COUNT=$((CONFIGURED_COUNT + 1))
                else
                  echo "⚠️  Prowlarr → Sonarr: Failed (HTTP $HTTP_CODE)"
                  echo "   Response: $(echo "$BODY" | head -c 200)"
                fi
              fi
            fi
            
            echo ""
            
            # Configure Radarr ↔ Prowlarr
            if [ "$RADARR_READY" = true ]; then
              TOTAL_COUNT=$((TOTAL_COUNT + 2))
              
              echo "=== Radarr ↔ Prowlarr Integration ==="
              
              # Check if Prowlarr indexer exists in Radarr
              EXISTING_INDEXER=$(curl -s -L -H "X-Api-Key: ${RADARR_KEY}" "${RADARR_URL}/api/v3/indexer" 2>/dev/null | jq -r '.[] | select(.implementation == "Prowlarr") | .id' | head -1 || echo "")
              
              if [ -n "$EXISTING_INDEXER" ]; then
                echo "✅ Radarr → Prowlarr: Already configured"
                CONFIGURED_COUNT=$((CONFIGURED_COUNT + 1))
              else
                echo "Configuring Radarr → Prowlarr..."
                # Get schema first
                SCHEMA=$(curl -s -L -H "X-Api-Key: ${RADARR_KEY}" "${RADARR_URL}/api/v3/indexer/schema" 2>/dev/null)
                PROWLARR_SCHEMA=$(echo "$SCHEMA" | jq -r '.[] | select(.implementation == "Prowlarr")')
                
                # Build proper JSON payload
                PAYLOAD=$(echo "$PROWLARR_SCHEMA" | jq --arg url "${PROWLARR_URL}" --arg key "${RADARR_KEY}" '{
                  name: .name,
                  implementation: .implementation,
                  configContract: .configContract,
                  enableRss: true,
                  enableAutomaticSearch: true,
                  enableInteractiveSearch: true,
                  priority: 25,
                  fields: (.fields | map(
                    if .name == "baseUrl" then .value = $url
                    elif .name == "apiKey" then .value = $key
                    elif .name == "syncLevel" then .value = "fullSync"
                    else if (.value == null) then .value = "" else . end
                    end
                  ))
                }')
                
                RESPONSE=$(curl -s -L -w "\n%{http_code}" -X POST \
                  -H "Content-Type: application/json" \
                  -H "X-Api-Key: ${RADARR_KEY}" \
                  -d "$PAYLOAD" \
                  "${RADARR_URL}/api/v3/indexer" 2>/dev/null || echo -e "\n000")
                HTTP_CODE=$(echo "$RESPONSE" | tail -1)
                BODY=$(echo "$RESPONSE" | head -n -1)
                if [ "$HTTP_CODE" = "201" ] || [ "$HTTP_CODE" = "200" ]; then
                  echo "✅ Radarr → Prowlarr: Configured"
                  CONFIGURED_COUNT=$((CONFIGURED_COUNT + 1))
                else
                  echo "⚠️  Radarr → Prowlarr: Failed (HTTP $HTTP_CODE)"
                  echo "   Response: $(echo "$BODY" | head -c 200)"
                fi
              fi
              
              # Check if Radarr application exists in Prowlarr
              EXISTING_APP=$(curl -s -L -H "X-Api-Key: ${PROWLARR_KEY}" "${PROWLARR_URL}/api/v1/applications" 2>/dev/null | jq -r '.[] | select(.name == "Radarr") | .id' | head -1 || echo "")
              
              if [ -n "$EXISTING_APP" ]; then
                echo "✅ Prowlarr → Radarr: Already configured"
                CONFIGURED_COUNT=$((CONFIGURED_COUNT + 1))
              else
                echo "Configuring Prowlarr → Radarr..."
                # Get schema for Radarr application
                SCHEMA=$(curl -s -L -H "X-Api-Key: ${PROWLARR_KEY}" "${PROWLARR_URL}/api/v1/applications/schema" 2>/dev/null)
                RADARR_SCHEMA=$(echo "$SCHEMA" | jq -r '.[] | select(.implementation == "Radarr")')
                
                # Build proper JSON payload
                PAYLOAD=$(echo "$RADARR_SCHEMA" | jq --arg url "${RADARR_URL}" --arg key "${RADARR_KEY}" '{
                  name: .name,
                  syncLevel: "addAndRemoveOnly",
                  implementation: .implementation,
                  configContract: .configContract,
                  fields: (.fields | map(
                    if .name == "baseUrl" then .value = $url
                    elif .name == "apiKey" then .value = $key
                    elif .name == "syncAppIndexers" then .value = true
                    elif .name == "appIndexersSyncLevel" then .value = "addAndRemoveOnly"
                    else if (.value == null) then .value = "" else . end
                    end
                  ))
                }')
                
                RESPONSE=$(curl -s -L -w "\n%{http_code}" -X POST \
                  -H "Content-Type: application/json" \
                  -H "X-Api-Key: ${PROWLARR_KEY}" \
                  -d "$PAYLOAD" \
                  "${PROWLARR_URL}/api/v1/applications" 2>/dev/null || echo -e "\n000")
                HTTP_CODE=$(echo "$RESPONSE" | tail -1)
                BODY=$(echo "$RESPONSE" | head -n -1)
                if [ "$HTTP_CODE" = "201" ] || [ "$HTTP_CODE" = "200" ]; then
                  echo "✅ Prowlarr → Radarr: Configured"
                  CONFIGURED_COUNT=$((CONFIGURED_COUNT + 1))
                else
                  echo "⚠️  Prowlarr → Radarr: Failed (HTTP $HTTP_CODE)"
                  echo "   Response: $(echo "$BODY" | head -c 200)"
                fi
              fi
            fi
            
            echo ""
            echo "=========================================="
            echo "Summary: $CONFIGURED_COUNT/$TOTAL_COUNT configurations applied"
            echo "=========================================="
            
            # Exit successfully if at least some configurations were applied or already existed
            exit 0
            EOF
        env:
        # Service URLs from ConfigMap
        - name: SONARR_URL
          valueFrom:
            configMapKeyRef:
              name: starr-common-config
              key: SONARR_URL
        - name: RADARR_URL
          valueFrom:
            configMapKeyRef:
              name: starr-common-config
              key: RADARR_URL
        - name: PROWLARR_URL
          valueFrom:
            configMapKeyRef:
              name: starr-common-config
              key: PROWLARR_URL
        # API Keys from Secret (optional - will skip if not available)
        - name: SONARR_API_KEY
          valueFrom:
            secretKeyRef:
              name: starr-secrets
              key: SONARR_API_KEY
              optional: true
        - name: RADARR_API_KEY
          valueFrom:
            secretKeyRef:
              name: starr-secrets
              key: RADARR_API_KEY
              optional: true
        - name: PROWLARR_API_KEY
          valueFrom:
            secretKeyRef:
              name: starr-secrets
              key: PROWLARR_API_KEY
              optional: true
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "200m"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: starr-integration-configurator
  namespace: media
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: starr-integration-configurator
  namespace: media
rules:
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: starr-integration-configurator
  namespace: media
subjects:
- kind: ServiceAccount
  name: starr-integration-configurator
  namespace: media
roleRef:
  kind: Role
  name: starr-integration-configurator
  apiGroup: rbac.authorization.k8s.io

