apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nas-development
  namespace: argocd
spec:
  project: nas
  source:
    repoURL: https://github.com/brettswift/k8s_nas.git
    targetRevision: dev    # Points to dev branch
    path: environments/development
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 