apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gluetun-config
  namespace: downloads
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi 