apiVersion: batch/v1
kind: CronJob
metadata:
  name: uptime-kuma-sync
  namespace: monitoring
  labels:
    app: uptime-kuma-sync
spec:
  schedule: "0 2 * * *"  # Run daily at 2 AM
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: uptime-kuma-sync
        spec:
          serviceAccountName: uptime-kuma-sync
          restartPolicy: OnFailure
          containers:
          - name: sync
            image: python:3.11-slim
            command:
            - /bin/bash
            - -c
            - |
              # Install dependencies
              apt-get update -qq && apt-get install -y -qq curl jq kubectl >/dev/null 2>&1
              pip install -q uptime-kuma-api >/dev/null 2>&1
              
              # Run Python sync script
              python3 /scripts/sync-monitors.py
            env:
            - name: UPTIME_KUMA_URL
              value: "http://uptime-kuma.monitoring.svc.cluster.local:3001"
            - name: UPTIME_KUMA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: uptime-kuma-api-key
                  key: api-key
            - name: UPTIME_KUMA_USERNAME
              valueFrom:
                secretKeyRef:
                  name: uptime-kuma-credentials
                  key: username
            - name: UPTIME_KUMA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: uptime-kuma-credentials
                  key: password
            - name: NAMESPACES
              value: "media homeautomation qbittorrent homepage"
            volumeMounts:
            - name: sync-script
              mountPath: /scripts
              readOnly: true
          volumes:
          - name: sync-script
            configMap:
              name: uptime-kuma-sync-python-script
              defaultMode: 0755

