apiVersion: batch/v1
kind: CronJob
metadata:
  name: sync-cert-secret
  namespace: argocd
spec:
  schedule: "*/5 * * * *"  # Every 5 minutes
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: cert-sync-sa
          restartPolicy: OnFailure
          containers:
          - name: sync-secret
            image: bitnami/kubectl:latest
            command:
            - /bin/bash
            - -c
            - |
              set -e
              SOURCE_NS="argocd"
              SECRET_NAME="home-brettswift-com-tls"
              
              # Get all namespaces that need the cert (ingress references)
              TARGET_NS=$(kubectl get ingress -A -o jsonpath='{range .items[*]}{.metadata.namespace}{"\t"}{.spec.tls[0].secretName}{"\n"}{end}' | grep "$SECRET_NAME" | cut -f1 | sort -u)
              
              echo "Syncing secret from $SOURCE_NS to:"
              echo "$TARGET_NS"
              echo ""
              
              for ns in $TARGET_NS; do
                if [ "$ns" != "$SOURCE_NS" ]; then
                  echo "Syncing to namespace: $ns"
                  kubectl get secret "$SECRET_NAME" -n "$SOURCE_NS" -o yaml | \
                    sed "s/namespace: $SOURCE_NS/namespace: $ns/" | \
                    sed '/^  uid:/d' | \
                    sed '/^  resourceVersion:/d' | \
                    sed '/^  selfLink:/d' | \
                    kubectl apply -f -
                  echo "✅ Synced to $ns"
                fi
              done
              
              echo ""
              echo "✅ Sync complete"
