apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns-home
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: brettswift@gmail.com
    privateKeySecretRef:
      name: letsencrypt-dns-home
    solvers:
    - dns01:
        route53:
          region: us-west-2
          # accessKeyID must be set manually - this is a placeholder
          # The setup script will patch this with the actual value
          accessKeyID: ""
          secretAccessKeySecretRef:
            name: route53-credentials
            key: secret-access-key

