apiVersion: batch/v1
kind: Job
metadata:
  name: sync-route53-credentials-hook
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  ttlSecondsAfterFinished: 300  # Clean up after 5 minutes
  template:
    spec:
      serviceAccountName: default
      restartPolicy: OnFailure
      containers:
      - name: sync-secret
        image: bitnami/kubectl:latest
        command:
        - /bin/bash
        - -c
        - |
          set -e
          SOURCE_NS="cert-manager"
          SECRET_NAME="route53-credentials"
          
          # Target namespaces that need route53 credentials
          TARGET_NS="external-dns"
          
          echo "🔄 ArgoCD PostSync Hook: Syncing $SECRET_NAME from $SOURCE_NS to: $TARGET_NS"
          echo ""
          
          for ns in $TARGET_NS; do
            if [ "$ns" != "$SOURCE_NS" ]; then
              echo "Syncing to namespace: $ns"
              kubectl get secret "$SECRET_NAME" -n "$SOURCE_NS" -o yaml | \
                sed "s/namespace: $SOURCE_NS/namespace: $ns/" | \
                sed '/^  uid:/d' | \
                sed '/^  resourceVersion:/d' | \
                sed '/^  selfLink:/d' | \
                sed '/^  creationTimestamp:/d' | \
                kubectl apply -f -
              echo "✅ Synced to $ns"
            fi
          done
          
          echo ""
          echo "✅ PostSync hook complete"

