apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cert-manager
  namespace: infrastructure
spec:
  selector:
    matchLabels:
      app: cert-manager
  endpoints:
    - port: metrics
      interval: 60s
  namespaceSelector:
    matchNames:
      - infrastructure 