apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-ingress
  namespace: infrastructure
spec:
  endpoints:
    - interval: 30s
      port: metrics
  selector:
    matchLabels:
      app: nginx-ingress 