apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-config-pv
  labels:
    app: jellyfin
    type: static
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /mnt/data/configs/jellyfin
    type: DirectoryOrCreate
  # claimRef will be set automatically when PVC binds
  # Leaving it unset allows PVC to bind on first creation

