apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-runner-scale-set-controller
  namespace: argocd
  labels:
    app.kubernetes.io/name: arc-runner-scale-set-controller
    category: infrastructure
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: infrastructure
  source:
    repoURL: ghcr.io/actions/actions-runner-controller-charts
    chart: gha-runner-scale-set-controller
    targetRevision: "0.10.1"
    helm:
      releaseName: arc-runner-scale-set-controller
  destination:
    server: https://kubernetes.default.svc
    namespace: arc-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
