apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure
  namespace: argocd
  labels:
    app.kubernetes.io/name: infrastructure
    category: infrastructure
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  source:
    repoURL: git@github.com:brettswift/k8s_nas.git
    targetRevision: new-argo
    path: apps/infrastructure
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  ignoreDifferences:
    # Ignore accessKeyID since it's injected manually (not stored in Git)
    - group: cert-manager.io
      kind: ClusterIssuer
      name: letsencrypt-dns-home
      jsonPointers:
        - /spec/acme/solvers/0/dns01/route53/accessKeyID
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
