apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infrastructure
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: production-cluster
        server: https://kubernetes.default.svc
        environment: production
  template:
    metadata:
      name: 'infrastructure-{{name}}'
      labels:
        app.kubernetes.io/name: infrastructure
        app.kubernetes.io/instance: '{{name}}'
        environment: '{{environment}}'
        category: "infrastructure"
    spec:
      project: infrastructure
      source:
        repoURL: git@github.com:brettswift/k8s_nas.git
        targetRevision: dev_starr
        path: apps/infrastructure
      destination:
        server: "{{server}}"
        namespace: cert-manager
      syncPolicy:
        automated:
          prune: true
          selfHeal: true

