apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: f1-predictor-dev

resources:
- namespace.yaml
- ../../base
- ingress.yaml

patches:
- target:
    kind: Job
    name: image-refresh
  patch: |
    - op: replace
      path: /spec/template/spec/containers/0/env/1/value
      value: "dev"

images:
- name: ghcr.io/brettswift/f1-predictor:latest
  newName: ghcr.io/brettswift/f1-predictor
  newTag: dev
